version: "0.2"
files:
  - src/**/*.css
  - examples/**/*.html
  - build.js
  - test/a11y.js
  - examples/scripts/**/*.js
  - package.json
ignorePaths:
  - src/bulma.css
words:
  - Ankrum
  - browserslistrc
  - bulma
  - flexbox
  - greyscale
  - gstatic
  - instantclick
  - jankrum
  - KHTML
  - lightningcss
  - oklch
  - Orgautomatech
  - Pico
  - stylesheet
  - WCAG
  - Yotam
